### ISSUE TITLE
ご連絡

### ISSUE THREAD

**Issue by Hikoyu** [nodchip/tanuki-#2]
第2回電竜戦バージョンの評価関数が本家やねうら王エンジンには対応していなくなっていたので、マニュアルビルドするようにmacOS向けのHomebrewの自作Formulaをアップデートしておきました。（ただし、M1 Macは未確認）
```
$ brew tap hikoyu/shogi
$ brew install tanuki
```

**Comment by nodchip** [comment]
ご連絡いただきありがとうございます。
本家やねうら王のほうにつきましては、 https://github.com/yaneurao/YaneuraOu/pull/212 にて、 tanuki- 第2回電竜戦バージョンの評価関数への対応が行われました。そちらのほうもご参照いただけると幸いです。
本 Issue は Close させて頂きたいと思います。
